"clean-containers":
  "description": "Garbage collect non-running containers"
"clean-images":
  "description": "Garbage collect non-running images"
  "options":
    "untagged":
      "type": "boolean"
      "description": "Only remove untagged"
      "default": !!bool "true"
"guestbook-example":
  "description": "Launch the guestbook example in your k8s cluster"
