"options":
  "enable-cgroups":
    "type": "boolean"
    "default": !!bool "false"
    "description": |
      Enable GRUB cgroup overrides cgroup_enable=memory swapaccount=1. WARNING
      changing this option will reboot the host - use with caution on production
      services
  "iface":
    "type": "string"
    "default": "eth0"
    "description": |
      Interface to bind flannel overlay networking to. Defaults to eth0.
  "cidr":
    "type": "string"
    "default": "10.1.0.0/16"
    "description": |
      Network CIDR to assign to Kubernetes service groups. This must not
      overlap with any IP ranges assigned to nodes for pods.
  "etcd_image":
    "type": "string"
    "default": "gcr.io/google_containers/etcd:2.0.12"
    "description": |
      The image to pull for the 'etcdctl' command. Recommended to
      mirror the default on a private registry if connectivity is a concern
  "flannel_image":
    "type": "string"
    "default": "quay.io/coreos/flannel:0.5.5"
    "description": |
      The image to pull for running 'flannel'. Recommended to
      mirror the default on a private registry if connectivity is a concern
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": "List of extra apt sources, per charm-helpers standard format (a\
      \ yaml list of strings encoded as a string). Each source may be either a line\
      \ that can be added directly to sources.list(5), or in the form ppa:<user>/<ppa-name>\
      \ for adding Personal Package Archives, or a distribution component to enable.\n"
    "type": "string"
    "default": ""
  "install_keys":
    "description": "List of signing keys for install_sources package sources, per\
      \ charmhelpers standard format (a yaml list of strings encoded as a string).\
      \ The keys should be the full ASCII armoured GPG public keys. While GPG key\
      \ ids are also supported and looked up on a keyserver, operators should be aware\
      \ that this mechanism is insecure. null can be used if a standard package signing\
      \ key is used that will already be installed on the machine, and for PPA sources\
      \ where the package signing key is securely retrieved from Launchpad.\n"
    "type": "string"
    "default": ""
  "root_certificate":
    "type": "string"
    "default": ""
    "description": |
      The root certificate to use for this grouping of charms.
      If empty (default) the leader will generate a self signed Certificate
      Authority (CA). All certificates will be based on the root certificate.
  "version":
    "type": "string"
    "default": "v1.2.3"
    "description": |
      The version of Kubernetes to use in this charm. The version is inserted
      in the configuration files that specify the hyperkube container to use
      when starting a Kubernetes cluster. Changing this value will restart the
      Kubernetes cluster.
  "dns_domain":
    "type": "string"
    "default": "cluster.local"
    "description": |
      The domain name to use for the Kubernetes cluster by the
      skydns service.
