options:
  ssl_ca:
    type: string
    default:
    description: |
      base64-encoded SSL CA to use with the certificate and key provided 
      to keystone - this is only required if you are providing a privately
      signed ssl_cert and ssl_key.
      This certificate will be provided to Contrail's keystone clients.
