"name": "docker"
"summary": "Docker container runtime subordinate"
"maintainer": "Joe Borg <joseph.borg@canonical.com>"
"description": |
  A Juju subordinate charm that can be attached to
  charms that need a container runtime.
"tags":
- "misc"
- "containers"
"series":
- "xenial"
- "bionic"
"requires":
  "docker":
    "interface": "container-runtime"
    "scope": "container"
  "docker-registry":
    "interface": "docker-registry"
"subordinate": !!bool "true"
